language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@3
script:
  - sbt compile coverage test coverageReport codacyCoverage
cache:
  directories:
    - "node_modules"
services:
  - mysql
after_success:
- npm run coveralls
