language: node_js

node_js:
  - "4"

before_install:
  - npm i -g npm@version-number

install:
  - npm install

cache:
  directories:
    - "node_modules"

services:
  - mysql
  test:
  adapter: mysql2
  database: library
  username: root
  encoding: utf8
