language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@3
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm rm --save-dev istanbul"
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
install:
  - npm install
before_script:
- "mysql -e 'create database test; select version();'"
script:
  - "npm test"
matrix:
  include:
    - node_js: '8'
      env: MYSQL_TYPE=mysql MYSQL_HOST=localhost MYSQL_DATABASE=node_mysql MYSQL_USER=root MYSQL_PASSWORD=
      addons: {mysql: '5.6.2'}
  allow_failures:
      - node_js: '8'
      env: MYSQL_TYPE=mysql MYSQL_HOST=localhost MYSQL_DATABASE=node_mysql MYSQL_USER=root MYSQL_PASSWORD=
      addons: {mysql: '5.6.2'}
sudo: false
cache:
  directories:
    - "node_modules"
services:
  - mysql
env:
  - MYSQL_TYPE=mysql MYSQL_HOST=localhost MYSQL_DATABASE=test MYSQL_USER=root MYSQL_PASSWORD=
test:
  adapter: mysql2
  database: test
  username: root
  encoding: utf8
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage && rm -rf ./coverage
  - bash <(curl -s https://codecov.io/bash)
