language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@3
script:
  - npm start
cache:
  directories:
    - "node_modules"
services:
  - mysql
after_success:
  - npm run coveralls
test:
  adapter: mysql2
  database: library
  username: root
  password: 13579ret
  encoding: utf8
