language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@3
install:
  - npm install
test_script:
  - "npm test"
cache:
  directories:
    - "node_modules"
services:
  - mysql
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage && rm -rf ./coverage
