language: node_js
node_js:
  - "8"
before_install:
  - npm i -g npm@3
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar $(curl https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r .assets[0].browser_download_url)
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm rm --save-dev istanbul"
  - "test $TRAVIS_NODE_VERSION != '0.8' || npm rm --save-dev istanbul"
install:
  - npm install
script:
  - "npm test"
cache:
  directories:
    - "node_modules"
services:
  - mysql
test:
  adapter: mysql2
  database: test
  username: root
  encoding: utf8
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage && rm -rf ./coverage
  - bash <(curl -s https://codecov.io/bash)
